# Generated by Django 5.1.1 on 2024-10-21 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(choices=[('Sacred Heart Medical Center', 'Sacred Heart Medical Center'), ('Angeles University Foundation Medical Center', 'Angeles University Foundation Medical Center')], max_length=50)),
                ('appointment_date', models.DateTimeField()),
                ('appointment_type', models.CharField(choices=[('Check-up', 'Check-up'), ('Consultation', 'Consultation')], max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('is_doctor', models.BooleanField(default=False)),
                ('assigned_hospital', models.CharField(choices=[('Sacred Heart Medical Center', 'Sacred Heart Medical Center'), ('Angeles University Foundation Medical Center', 'Angeles University Foundation Medical Center')], default='Sacred Heart Medical Center', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('medical_records_photo', models.ImageField(blank=True, null=True, upload_to='medical_records/')),
                ('verification_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
